### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by BUI-studies** [ohiienko-r/js-07-exmpl-and-hw#1]
## [task-01](https://github.com/ohiienko-r/js-07-exmpl-and-hw/blob/main/task-01.js)
Є відповідний [метод](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill) масиву який вміє таке робити як тобі тут треба

## [task-02](https://github.com/ohiienko-r/js-07-exmpl-and-hw/blob/main/task-02.js)
Є відповідний [метод](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) масиву який вміє таке робити як тобі тут треба

## [task-03](https://github.com/ohiienko-r/js-07-exmpl-and-hw/blob/main/task-03.js)
Все ок, це навіть більш продвинуто ніж я розраховував, але якшо шо то є метод [concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

**Comment by ohiienko-r** [comment]
0) Проблема в тому, що про це ніде не написано, але метод fill не дуже працює на пустому масиві. Вважаю атата незарахованим.

1)Треба допомога із тим як мені за допомогою sort() реверснути масив. Гугл нічого не підказав окрім методу reverse() який за умовою не можна використовувати.

**Comment by BUI-studies** [comment]
0) атата зараховується, бо у функцію `new Arra()` ти можеш передати довжину масиву
1) оце атата можемо вважати не зарахованим, бо до мене тіки шо дійшло шо це не так просто як здається)

**Comment by ohiienko-r** [comment]
0. Все рівно не розумію. Коли я оголошую новий пустий масив на ньому fill не працює, бо як каже дока: 
"The fill() method changes all elements in an array to a static value, from a start index (default 0) to an end index (default array.length). It returns the modified array."

А в мене в масиві нема взагалі елементів поки шо.

**Comment by BUI-studies** [comment]
спробуй пошукати "як створити пустий самив первної довжини"

**Comment by ohiienko-r** [comment]
![image](https://user-images.githubusercontent.com/109099364/235651071-e762bb5f-e4bc-45d2-9392-6fa69c9f6073.png)
